//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiVideoClub.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Actores()
        {
            this.Actores_Peliculas_Incremental = new HashSet<Actores_Peliculas_Incremental>();
            this.Actores_Peliculas_PK = new HashSet<Actores_Peliculas_PK>();
        }
    
        public int idActores { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actores_Peliculas_Incremental> Actores_Peliculas_Incremental { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actores_Peliculas_PK> Actores_Peliculas_PK { get; set; }
    }
}
