//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiVideoClub.Models.ViewModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ejercicioVideoclubEntities : DbContext
    {
        public ejercicioVideoclubEntities()
            : base("name=ejercicioVideoclubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actores> Actores { get; set; }
        public virtual DbSet<Actores_Peliculas_Incremental> Actores_Peliculas_Incremental { get; set; }
        public virtual DbSet<Actores_Peliculas_PK> Actores_Peliculas_PK { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Peliculas> Peliculas { get; set; }
    }
}
